more debugging

diff --git a/scripts/brig-build b/scripts/brig-build
--- a/scripts/brig-build
+++ b/scripts/brig-build
@@ -72,10 +72,15 @@ echo  "Current directory: "`pwd`
 
 echo "Building zip ${archive_name} ..."
 
+if [ ! -f 'src/test_lambda_function.py' ]; then
+  echo "Missing test file in `pwd`/src before cp -Rp src/ stg/ "
+  exit 1
+fi
+
 cp -Rp src/ stg/
 
 if [ ! -f 'stg/test_lambda_function.py' ]; then
-  echo "Missing test file in `pwd` after cp -Rp src/ stg/ "
+  echo "Missing test file in `pwd`/stg after cp -Rp src/ stg/ "
   exit 1
 fi
 
