more debugging

diff --git a/scripts/brig-build b/scripts/brig-build
--- a/scripts/brig-build
+++ b/scripts/brig-build
@@ -91,9 +91,19 @@ pushd stg > /dev/null
 
 if [ -e "../requirements.txt" ]; then
 
+    if [ ! -f 'test_lambda_function.py' ]; then
+      echo "Missing test file in `pwd` before pip install -t "
+      exit 1
+    fi
+
     echo "Installing requirements ..."
 
     pip install --ignore-installed --no-clean -r ../requirements.txt -t ./
+
+    if [ ! -f 'test_lambda_function.py' ]; then
+      echo "Missing test file in `pwd` after pip install -t "
+      exit 1
+    fi
 
     echo "Requirements installed."
 
@@ -105,7 +115,18 @@ fi
 
 chmod -R 755 .
 
+if [ ! -f 'test_lambda_function.py' ]; then
+  echo "Missing test file in `pwd` before zip"
+  exit 1
+fi
+
 zip -r ../${archive_name} .
+
+if [ ! -f 'test_lambda_function.py' ]; then
+  echo "Missing test file in `pwd` after zip"
+  exit 1
+fi
+
 
 popd  > /dev/null
 
